// flow-typed signature: e3d589e652f201db1ae266efeb4f0d10
// flow-typed version: <<STUB>>/node-bme280_v^0.1.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-bme280'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-bme280' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-bme280/BME280' {
  declare module.exports: any;
}

declare module 'node-bme280/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-bme280/BME280.js' {
  declare module.exports: $Exports<'node-bme280/BME280'>;
}
declare module 'node-bme280/gulpfile.js' {
  declare module.exports: $Exports<'node-bme280/gulpfile'>;
}
