// flow-typed signature: bd952957a0dbd4acb730634d614564dd
// flow-typed version: <<STUB>>/node-zabbix-sender_v^1.0.8/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-zabbix-sender'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-zabbix-sender' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-zabbix-sender/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-zabbix-sender/example.js' {
  declare module.exports: $Exports<'node-zabbix-sender/example'>;
}
declare module 'node-zabbix-sender/index' {
  declare module.exports: $Exports<'node-zabbix-sender'>;
}
declare module 'node-zabbix-sender/index.js' {
  declare module.exports: $Exports<'node-zabbix-sender'>;
}
