// flow-typed signature: 049c412f30632ea4d7385104fd8f4a8a
// flow-typed version: <<STUB>>/node-cron_v^1.2.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-cron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-cron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-cron/src/convert-expression/asterisk-to-range-conversion' {
  declare module.exports: any;
}

declare module 'node-cron/src/convert-expression/index' {
  declare module.exports: any;
}

declare module 'node-cron/src/convert-expression/month-names-conversion' {
  declare module.exports: any;
}

declare module 'node-cron/src/convert-expression/range-conversion' {
  declare module.exports: any;
}

declare module 'node-cron/src/convert-expression/step-values-conversion' {
  declare module.exports: any;
}

declare module 'node-cron/src/convert-expression/week-day-names-conversion' {
  declare module.exports: any;
}

declare module 'node-cron/src/node-cron' {
  declare module.exports: any;
}

declare module 'node-cron/src/pattern-validation' {
  declare module.exports: any;
}

declare module 'node-cron/src/scheduled-task' {
  declare module.exports: any;
}

declare module 'node-cron/src/task' {
  declare module.exports: any;
}

declare module 'node-cron/test/convert-expression/asterisk-to-range-conversion-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/convert-expression/convert-expression-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/convert-expression/month-names-conversion-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/convert-expression/range-conversion-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/convert-expression/step-values-conversion-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/convert-expression/week-day-names-conversion-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/defer-start-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/destroy-task-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/multiples-values-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/range-values-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/restart-task-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/scheduling-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/step-value-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/stop-task-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/task-day-of-month-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/task-fail-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/task-hour-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/task-minute-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/task-month-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/task-second-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/task-week-day-day-of-month-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/task-week-day-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/validate-day-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/validate-hours-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/validate-minute-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/validate-month-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/validate-second-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/validate-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/validate-week-day-test' {
  declare module.exports: any;
}

declare module 'node-cron/test/valitate-taks-schaduling-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-cron/src/convert-expression/asterisk-to-range-conversion.js' {
  declare module.exports: $Exports<'node-cron/src/convert-expression/asterisk-to-range-conversion'>;
}
declare module 'node-cron/src/convert-expression/index.js' {
  declare module.exports: $Exports<'node-cron/src/convert-expression/index'>;
}
declare module 'node-cron/src/convert-expression/month-names-conversion.js' {
  declare module.exports: $Exports<'node-cron/src/convert-expression/month-names-conversion'>;
}
declare module 'node-cron/src/convert-expression/range-conversion.js' {
  declare module.exports: $Exports<'node-cron/src/convert-expression/range-conversion'>;
}
declare module 'node-cron/src/convert-expression/step-values-conversion.js' {
  declare module.exports: $Exports<'node-cron/src/convert-expression/step-values-conversion'>;
}
declare module 'node-cron/src/convert-expression/week-day-names-conversion.js' {
  declare module.exports: $Exports<'node-cron/src/convert-expression/week-day-names-conversion'>;
}
declare module 'node-cron/src/node-cron.js' {
  declare module.exports: $Exports<'node-cron/src/node-cron'>;
}
declare module 'node-cron/src/pattern-validation.js' {
  declare module.exports: $Exports<'node-cron/src/pattern-validation'>;
}
declare module 'node-cron/src/scheduled-task.js' {
  declare module.exports: $Exports<'node-cron/src/scheduled-task'>;
}
declare module 'node-cron/src/task.js' {
  declare module.exports: $Exports<'node-cron/src/task'>;
}
declare module 'node-cron/test/convert-expression/asterisk-to-range-conversion-test.js' {
  declare module.exports: $Exports<'node-cron/test/convert-expression/asterisk-to-range-conversion-test'>;
}
declare module 'node-cron/test/convert-expression/convert-expression-test.js' {
  declare module.exports: $Exports<'node-cron/test/convert-expression/convert-expression-test'>;
}
declare module 'node-cron/test/convert-expression/month-names-conversion-test.js' {
  declare module.exports: $Exports<'node-cron/test/convert-expression/month-names-conversion-test'>;
}
declare module 'node-cron/test/convert-expression/range-conversion-test.js' {
  declare module.exports: $Exports<'node-cron/test/convert-expression/range-conversion-test'>;
}
declare module 'node-cron/test/convert-expression/step-values-conversion-test.js' {
  declare module.exports: $Exports<'node-cron/test/convert-expression/step-values-conversion-test'>;
}
declare module 'node-cron/test/convert-expression/week-day-names-conversion-test.js' {
  declare module.exports: $Exports<'node-cron/test/convert-expression/week-day-names-conversion-test'>;
}
declare module 'node-cron/test/defer-start-test.js' {
  declare module.exports: $Exports<'node-cron/test/defer-start-test'>;
}
declare module 'node-cron/test/destroy-task-test.js' {
  declare module.exports: $Exports<'node-cron/test/destroy-task-test'>;
}
declare module 'node-cron/test/multiples-values-test.js' {
  declare module.exports: $Exports<'node-cron/test/multiples-values-test'>;
}
declare module 'node-cron/test/range-values-test.js' {
  declare module.exports: $Exports<'node-cron/test/range-values-test'>;
}
declare module 'node-cron/test/restart-task-test.js' {
  declare module.exports: $Exports<'node-cron/test/restart-task-test'>;
}
declare module 'node-cron/test/scheduling-test.js' {
  declare module.exports: $Exports<'node-cron/test/scheduling-test'>;
}
declare module 'node-cron/test/step-value-test.js' {
  declare module.exports: $Exports<'node-cron/test/step-value-test'>;
}
declare module 'node-cron/test/stop-task-test.js' {
  declare module.exports: $Exports<'node-cron/test/stop-task-test'>;
}
declare module 'node-cron/test/task-day-of-month-test.js' {
  declare module.exports: $Exports<'node-cron/test/task-day-of-month-test'>;
}
declare module 'node-cron/test/task-fail-test.js' {
  declare module.exports: $Exports<'node-cron/test/task-fail-test'>;
}
declare module 'node-cron/test/task-hour-test.js' {
  declare module.exports: $Exports<'node-cron/test/task-hour-test'>;
}
declare module 'node-cron/test/task-minute-test.js' {
  declare module.exports: $Exports<'node-cron/test/task-minute-test'>;
}
declare module 'node-cron/test/task-month-test.js' {
  declare module.exports: $Exports<'node-cron/test/task-month-test'>;
}
declare module 'node-cron/test/task-second-test.js' {
  declare module.exports: $Exports<'node-cron/test/task-second-test'>;
}
declare module 'node-cron/test/task-week-day-day-of-month-test.js' {
  declare module.exports: $Exports<'node-cron/test/task-week-day-day-of-month-test'>;
}
declare module 'node-cron/test/task-week-day-test.js' {
  declare module.exports: $Exports<'node-cron/test/task-week-day-test'>;
}
declare module 'node-cron/test/validate-day-test.js' {
  declare module.exports: $Exports<'node-cron/test/validate-day-test'>;
}
declare module 'node-cron/test/validate-hours-test.js' {
  declare module.exports: $Exports<'node-cron/test/validate-hours-test'>;
}
declare module 'node-cron/test/validate-minute-test.js' {
  declare module.exports: $Exports<'node-cron/test/validate-minute-test'>;
}
declare module 'node-cron/test/validate-month-test.js' {
  declare module.exports: $Exports<'node-cron/test/validate-month-test'>;
}
declare module 'node-cron/test/validate-second-test.js' {
  declare module.exports: $Exports<'node-cron/test/validate-second-test'>;
}
declare module 'node-cron/test/validate-test.js' {
  declare module.exports: $Exports<'node-cron/test/validate-test'>;
}
declare module 'node-cron/test/validate-week-day-test.js' {
  declare module.exports: $Exports<'node-cron/test/validate-week-day-test'>;
}
declare module 'node-cron/test/valitate-taks-schaduling-test.js' {
  declare module.exports: $Exports<'node-cron/test/valitate-taks-schaduling-test'>;
}
